# Generated by Django 4.0.6 on 2022-07-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atampa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
