# Generated by Django 4.0.6 on 2022-07-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_atampa'),
    ]

    operations = [
        migrations.AddField(
            model_name='atampa',
            name='quality',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
