# Generated by Django 4.0.6 on 2022-07-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_comments_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='message',
            new_name='customer_message',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='subject',
            new_name='customer_subject',
        ),
    ]
